apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: spring-boot-ui-github-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      bindings:
        - ref: spring-boot-ui-pipeline-binding
      template:
        ref: spring-boot-ui-trigger-pipeline-template
