apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    eventlistener: spring-boot-ui-github-listener-interceptor
  name: spring-boot-ui-github-listener-el
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-spring-boot-ui-github-listener-interceptor

