kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: people-2
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: people-2
    apiVersion: apps.openshift.io/v1
  minReplicas: 3
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      selectPolicy: Max
      policies:
        - type: Pods
          value: 7
          periodSeconds: 10
    scaleDown:
      selectPolicy: Max
      policies:
        - type: Pods
          value: 3
          periodSeconds: 60
