apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: postgresql-operator-dev4devs-com
  namespace: demo
spec:
  channel: alpha
  name: postgresql-operator-dev4devs-com
  sourceNamespace: openshift-marketplace 
  installPlanApproval: Automatic
  source: community-operators
  sourceNamespace: openshift-marketplace
